export const Location = [
  { label: "Delhi", inputValue: "delhi" },
  { label: "Mumbai", inputValue: "mumbai" },
  { label: "Kolkata", inputValue: "kolkata" },
  { label: "Chennai", inputValue: "chennai" },
  { label: "Bengaluru", inputValue: "bengaluru" },
  { label: "Hyderabad", inputValue: "hyderabad" },
  { label: "Pune", inputValue: "pune" },
  { label: "Ahmedabad", inputValue: "ahmedabad" },
  { label: "Jaipur", inputValue: "jaipur" },
  { label: "Lucknow", inputValue: "lucknow" },
  { label: "Chandigarh", inputValue: "chandigarh" },
  { label: "Bhopal", inputValue: "bhopal" },
  { label: "Indore", inputValue: "indore" },
  { label: "Nagpur", inputValue: "nagpur" },
  { label: "Patna", inputValue: "patna" },
  { label: "Kanpur", inputValue: "kanpur" },
  { label: "Surat", inputValue: "surat" },
  { label: "Varanasi", inputValue: "varanasi" },
  { label: "Thiruvananthapuram", inputValue: "thiruvananthapuram" },
  { label: "Coimbatore", inputValue: "coimbatore" },
  { label: "Mysuru", inputValue: "mysuru" },
];
